# WHERE (IN E NOT IN)

# 1. INTRODUÇÃO

# O COMANDO WHERE PODE SER USADO EM CONJUNTO COM O IN OU O NOT IN COMO ALTERNATIVA AO OPERADOR LÓGICO OR. COM ELE, É POSSÍVEL FILTRAR APENAS AS LINHAS QUE CONTENHAM UM DOS VALORES ESPECIFICADOS EM UMA LISTA DE VALORES.

# 2. SINTAXE
# select COLUNA1, COLUNA2, COLUNA3
# FROM TABELA
# WHERE COLUNA1 IN (VALOR1, VALOR2, VALOR3);

-- WHERE COLUNA1= VALOR1 OR COLUNA1 = VALOR2 OR COLUNA1 = VALOR3;

# EXEMPLO. FAÇA UM FILTRO QUE RETORNE TODOS OS PRODUTOS DE UMA DAS 3 MARCAS A SEGUIR: DELL, SONY OU ALTURA.

select *
from produtos
where Marca_Produto NOT in ('DELL','SONY','ALTURA');

