# GROUP BY  + WHERE: CRIANDO FILTROS ANTES DOS AGRUPAMENTOS NO MySQL

# CONSEGUIMOS UTILIZAR O WHERE EM CONJUNTO COM O GROUP BY PARA CRIAR FILTROS ANTES DE REALIZAR OS AGRUPAMENTOS. POR EXEMPLO, MOSTRAR O TOTAL DE CLIENTES POR ESCOLARIDADE, SÓ QUE APENAS OS CLIENTES DO SEXO FEMININO. 


# EXEMPLO 1. CRIE UM AGRUPAMENTO MOSTRANDO O TOTAL DE CLIENTES POR ESCOLARIDADE, MAS APENAS OS CLIENTES DO SEXO FEMININO. 

select* FROM clientes;

select Escolaridade, count(*) as 'Qtd Clientes'
from clientes
where Sexo = 'F'
group by Escolaridade;